/** IPC channel names shared between the main and renderer processes. */
export const IPC = {
  scan: 'cem:scan',
  diagnose: 'cem:diagnose',
  remediationPropose: 'cem:remediation:propose',
  remediationApply: 'cem:remediation:apply',
  listMcp: 'cem:mcp:list',
  mcpExport: 'cem:mcp:export',
  mcpImport: 'cem:mcp:import',
  mcpToggle: 'cem:mcp:toggle',
  mcpRemove: 'cem:mcp:remove',
  listSkills: 'cem:skills:list',
  listAgents: 'cem:agents:list',
  tokens: 'cem:tokens',
  usageReport: 'cem:usage:report',
  planExport: 'cem:plan:export',
  listProfiles: 'cem:profiles:list',
  createProfile: 'cem:profiles:create',
  deleteProfile: 'cem:profiles:delete',
  profileTemplates: 'cem:profiles:templates',
  backup: 'cem:backup',
  readManifest: 'cem:restore:manifest',
  verify: 'cem:restore:verify',
  restorePlan: 'cem:restore:plan',
  restore: 'cem:restore:run',
  pickFile: 'cem:dialog:pickFile',
  pickDirectory: 'cem:dialog:pickDirectory',
  getConfig: 'cem:config:get',
  saveConfig: 'cem:config:save',
  platformInfo: 'cem:platform',
  openExternal: 'cem:openExternal',
  listHistory: 'cem:history:list',
  auditLog: 'cem:history:audit',
  syncStatus: 'cem:sync:status',
  syncInit: 'cem:sync:init',
  syncPush: 'cem:sync:push',
  syncPull: 'cem:sync:pull',
  updateCheck: 'cem:update:check',
  updateDownload: 'cem:update:download',
  updateInstall: 'cem:update:install',
  updatePreBackup: 'cem:update:preBackup',
  /** Event channel: main → renderer update status pushes. */
  updateStatus: 'cem:update:status',
  inventoryLoad: 'cem:inventory:load',
  inventoryCollect: 'cem:inventory:collect',
  inventoryLoadFile: 'cem:inventory:loadFile',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];
